site_name: EverLayout Documentation
pages:
  - Getting Started: index.md
  - Writing Layouts: writing.md
  - Reading Layouts: reading.md
  - Layout Formats: formats.md
  - EverLayout Bridge: bridge.md

theme: readthedocs
